language: objective-c

before_install:
  - brew update
  - brew install openssl
  - brew install cryptopp
  - brew install python
  - brew install python3
  - pip install coverage coveralls
  - python setup.py install

script:
  - coverage run --include="storjdemo/*" setup.py test  -a "--doctest-modules --pep8 -v tests/ storjdemo/"

after_success:
  - coverage report -m --include="storjdemo/*"
  - coveralls
